"""empty message

Revision ID: 043a6de455d2
Revises: e8e30a90cfa7
Create Date: 2024-02-07 23:53:11.521711

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '043a6de455d2'
down_revision = 'e8e30a90cfa7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('affirmations')
    op.drop_table('journal_entries_tags')
    op.drop_table('tags')
    op.drop_table('analytics')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analytics',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('mood_type_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('period', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['mood_type_id'], ['moods.id'], name='analytics_mood_type_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='analytics_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='analytics_pkey')
    )
    op.create_table('tags',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('tags_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('tag_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='tags_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('journal_entries_tags',
    sa.Column('entry_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tag_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['journal_entries.id'], name='journal_entries_tags_entry_id_fkey'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name='journal_entries_tags_tag_id_fkey'),
    sa.PrimaryKeyConstraint('entry_id', 'tag_id', name='journal_entries_tags_pkey')
    )
    op.create_table('affirmations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('source', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='affirmations_pkey')
    )
    # ### end Alembic commands ###
